version: 0.2

phases:
  nodejs: 12.x
  install_client:
    commands:
      - cd client
      - yarn install
  install_server:
    commands:
      - cd server
      - yarn install
  build_client:
    commands:
      - cd client
      - yarn build
