version: 0.2

phases:
  install:
    commands:
      - cd client
      - yarn install --production
      - cd ..
      - cd server
      - yarn install --production
      - cd ..
  build:
    commands:
      - yarn build
artifacts:
  files:
    - '**/*'
