module.exports = [
  {
    name: 'development',
    type: 'postgres',
    host: process.env.RDS_HOSTNAME,
    port: process.env.RDS_PORT,
    username: process.env.RDS_USERNAME,
    password: process.env.RDS_PASSWORD,
    database: process.env.RDS_DB_NAME,
    synchronize: true,
    logging: false,
    entities: ['src/entities/**/*.ts'],
    migrations: ['src/migrations/**/*.ts'],
    subscribers: ['src/subscribers/**/*.ts'],
    cli: {
      entitiesDir: 'src/entities',
      migrationsDir: 'src/migrations',
      subscribersDir: 'src/subscribers',
    },
  },
  {
    name: 'production',
    type: 'postgres',
    host: process.env.RDS_HOSTNAME,
    port: process.env.RDS_PORT,
    username: process.env.RDS_USERNAME,
    password: process.env.RDS_PASSWORD,
    database: process.env.RDS_DB_NAME,
    synchronize: true,
    logging: false,
    entities: ['build/entities/**/*.js'],
    migrations: ['build/migrations/**/*.js'],
    subscribers: ['build/subscribers/**/*.js'],
    cli: {
      entitiesDir: 'build/entities',
      migrationsDir: 'build/migrations',
      subscribersDir: 'build/subscribers',
    },
  },
];
